version: "3.8"
services:
  stock_analyser_service:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - .:/Stock_Analyser_dockerized:cached
      

    ports:
      - "8000:8000"
    image: stock_analyser_service:stock_analyser
    container_name: stock_analyser_service